Fixing the looping issue #4

diff --git a/.github/workflows/target_workflow.yml b/.github/workflows/target_workflow.yml
--- a/.github/workflows/target_workflow.yml
+++ b/.github/workflows/target_workflow.yml
@@ -38,9 +38,16 @@ jobs:
             https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
             -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}")
 
-          # Extract the workflow run ID from the response
-          target_workflow_id=$(echo $response | jq -r '.workflow_run.id')
-          echo "target_workflow_id=$target_workflow_id" >> $GITHUB_OUTPUT
+          # Check the response status code
+          status_code=$(echo $response | jq -r '.status_code')
+          if [ "$status_code" == "202" ]; then
+            echo "Target workflow triggered successfully"
+            target_workflow_id=$(echo $response | jq -r '.workflow_run.id')
+            echo "target_workflow_id=$target_workflow_id" >> $GITHUB_OUTPUT
+          else
+            echo "Failed to trigger target workflow: $response"
+            exit 1
+          fi
 
 
       - name: Wait for Target Workflow
@@ -72,9 +79,9 @@ jobs:
             elapsed_time=$((current_time - start_time))
             if [ $elapsed_time -gt 300 ]; then # 5 minutes
               echo "Timeout reached while waiting for target workflow"
-              break
+              exit 1 # Fail the step
             fi
-            
+
             sleep 10
           done
 
